### ISSUE TITLE
[Discussion] Concern about pagy_cursor_has_more

### ISSUE THREAD

**Issue by yunanhelmy** [Uysim/pagy-cursor#15]
Hi @Uysim,

I dug some of codes and found that you are querying again to check whether pagination has_more or not. It is from `pagy_cursor_has_more?`. So basically the query called twice.

Should it just become one query only instead of two queries?

Currently the limit is **pagy.items**. Let's just say that I call query `pagy_cursor_get_items` but limit should be changed **pagy.items + 1**.  So if we change the way we get the **has_more page** is to check whether collection.size > pagy.items :

- If  collection.size > pagy.items, has_more is true
- Otherwise has_more is false

Then the result would be same, but the query only happens once.

What do you think?

**Comment by Uysim** [comment]
@yunanhelmy nice idea

**Comment by Uysim** [comment]
I will try implement this. But if you can help in this pull request it would be nice

**Comment by yunanhelmy** [comment]
Sure I can help with PR.

**Comment by Uysim** [comment]
@yunanhelmy thank you. I'm waiting

**Comment by chrisauclair** [comment]
Is there any plan to release a new version that includes this change?

**Comment by Uysim** [comment]
@chrisauclair 
I think we have this at version 0.2.0

**Comment by chrisauclair** [comment]
@Uysim I'm using 0.2.0 and it still has the old version of `pagy_cursor_has_more?`

**Comment by mcmegavolt** [comment]
@Uysim Could you update the version with the fixes, please?

**Comment by Uysim** [comment]
@chrisauclair and @mcmegavolt  
Sorry my bad. I just release 0.2.1 a moment ago and it include this has more prevent re-query.
