### ISSUE TITLE
How to create front-end navigation links?

### ISSUE THREAD

**Issue by sedubois** [Uysim/pagy-cursor#21]
Our Rails app uses the following pagy navigation, which renders a limited number of testimonials, plus two "previous" and "next" navigation buttons:

```rb
# testimonials_controller.rb
def index
  @pagy, @testimonials = pagy(Testimonial.with_translations, items: 30)
end

# testimonials/index.html.slim
= render @testimonials
- link, p_prev, p_next = pagy_link_proc(@pagy), @pagy.prev, @pagy.next
== link.call p_prev, t('navigation.previous'), 'aria-label="prev" class="page prev"' if p_prev
== link.call p_next, t('navigation.next'), 'aria-label="next" class="page next"' if p_next
```

Now I would like to use `pagy-cursor` with before/after params instead of page numbers, for two reasons:
- To [avoid](https://use-the-index-luke.com/no-offset) SQL offsets;
- To implement a back link when viewing a Testimonial: the collection of testimonials should be rendered in a way as to include the just-viewed Testimonial. E.g. if I was viewing the testimonial `abc`, the back link should be something like `/testimonials?at=abc` (where `abc` would be the testimonial's UUID).

Based on the README I need to change the controller as follows:

```diff
# testimonials_controller.rb
- @pagy, @testimonials = pagy(Testimonial.with_translations, items: 30)
+ @pagy, @testimonials = pagy_uuid_cursor(Testimonial.with_translations, items: 30)
```

But how should the view code be adapted to make this work?

NB: pagy's default recommendation to render navigation links is `== pagy_nav(@pagy)`, however that code yields the error `undefined method `-' for nil:NilClass`.

Thank you very much for your help and all the best in spreading this gem 👍

**Comment by Uysim** [comment]
@sedubois 
To create the front-end link you might need to do it like this

**Controller**
```
pagy_uuid_cursor(Testimonial.with_translations, after: params[:after], before: params[:before])
```

**View**
```
= link_to 'Next', url_for(after: @ testimonials.last.id)
= link_to 'Prev', url_for(before: @ testimonials.first.id)
```

Hope this might help

**Comment by raszi** [comment]
I believe it would be better for the users if you could also override the generated links otherwise this whole solution cannot be a drop-in replacement.
