### ISSUE TITLE
Incompatible with Pagy 5

### ISSUE THREAD

**Issue by MarcelEeken** [Uysim/pagy-cursor#26]
Pagy 5.0 was released just a couple of days ago, and that has a breaking change with regards to `Pagy::VARS`. This variable has been renamed to `Page::DEFAULT` as can be seen in this changelog https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md#version-500

**Comment by Uysim** [comment]
@MarcelEeken 
I'll look into it as soon as possible. PR is welcome

**Comment by MarcelEeken** [comment]
If I have some time I will see if I can open one

**Comment by Ahmedhemaz** [comment]
when will pagy 5 support be merged?

**Comment by Uysim** [comment]
I am sorry for the delay. This support is schedule to release on 9 Feb 2022. 
FYI @Ahmedhemaz and @MarcelEeken

**Comment by Ahmedhemaz** [comment]
> 

Thanks a lot for your contributions

**Comment by Uysim** [comment]
Checkout our release [0.5.0](https://github.com/Uysim/pagy-cursor/releases/tag/0.5.0)

**Comment by MarcelEeken** [comment]
Thank you for the fix
