### ISSUE TITLE
Update README with development / contribution instructions?

### ISSUE THREAD

**Issue by corroded** [Uysim/pagy-cursor#5]
Hi, I am currently trying to make a PR for a bug I found and I just had some initial friction with setting up the test suite. Maybe I am not doing things right but when I tried to clone then do a bundle install, it complained because the repo does not have a Gemfile. I had to copy the AR5.2 gemfile into the root folder and rename it `Gemfile`.

Also, I am using pg so I just removed sqlite and mysql from the setup and changed the default `ENV['DB']` to `postgresql`. Again, I am unsure what to do here so I just fixed these in my fork (didn't commit) since I don't know how to run this in dev mode. Can you please update? :) Cheers!

**Comment by Uysim** [comment]
@corroded I'll review on it soon.
