### ISSUE TITLE
Require statement(s) in pagy initializer not documented in README

### ISSUE THREAD

**Issue by abevoelker** [Uysim/pagy-cursor#8]
First, thanks so much for the gem.

One thing you may want to add to the README instructions is adding the necessary require statement(s) to the pagy initializer:

```ruby
require "pagy_cursor/pagy/extras/cursor"
require "pagy_cursor/pagy/extras/uuid_cursor"
```

At least, `pagy_cursor` didn't work for me in my Rails app until I added the first line to `config/initializers/pagy.rb`. Thanks again.

**Comment by Uysim** [comment]
@abevoelker We have mention it here since the first place https://github.com/Uysim/pagy-cursor#usage. Am I correct?

**Comment by abevoelker** [comment]
Not quite. Just doing what the README says:

```ruby
require "pagy_cursor"
```

results in this error for me:

```ruby
undefined method `pagy_cursor' for #<FoosController:0x000055b7076287e8>
```

This fixed the error:

```ruby
require "pagy_cursor/pagy/extras/cursor"
```

Which I found by reading your specs: https://github.com/Uysim/pagy-cursor/blob/13a2503a4249a5a4313aea8ed008ebc6f87452e7/spec/pagy_cursor/cursor_spec.rb#L2

**Comment by Uysim** [comment]
Thanks @abevoelker  now I updated the read me
